// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class DALTemplate : DataTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data;\r\nusing Entit" +
                    "ies;\r\nusing CodeGeneratorResult;\r\n\r\nnamespace DAL\r\n{\r\n");
            
            #line 14 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
    var ObjectData = templateData.ObjectData;
    var DeleteProcedureTemplate = templateData.ProcedureDataList["PR_DELETE"];
    var GetAllProcedureTemplate = templateData.ProcedureDataList["PR_GET_ALL"];
    var GetProcedureTemplate = templateData.ProcedureDataList["PR_GET"];
    var InsertProcedureTemplate = templateData.ProcedureDataList["PR_INSERT"];
    var UpdateProcedureTemplate = templateData.ProcedureDataList["PR_UPDATE"];
 
            
            #line default
            #line hidden
            this.Write("    public partial class ");
            
            #line 21 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.ObjectName));
            
            #line default
            #line hidden
            this.Write("DAL : IDAL<");
            
            #line 21 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.EntityName));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n\t\tIDbConnection Connection;\r\n\r\n        public ");
            
            #line 25 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.ObjectName));
            
            #line default
            #line hidden
            this.Write("DAL(IDbConnection connection)\r\n        {\r\n            Connection = connection;\r\n " +
                    "       }\r\n\r\n        private const String UPDATE_");
            
            #line 30 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 30 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UpdateProcedureTemplate.PackageName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 30 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UpdateProcedureTemplate.ProcedureName));
            
            #line default
            #line hidden
            this.Write("\";\r\n        private const String GET_");
            
            #line 31 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 31 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetProcedureTemplate.PackageName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 31 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetProcedureTemplate.ProcedureName));
            
            #line default
            #line hidden
            this.Write("\";\r\n        private const String INSERT_");
            
            #line 32 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 32 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(InsertProcedureTemplate.PackageName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 32 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(InsertProcedureTemplate.ProcedureName));
            
            #line default
            #line hidden
            this.Write("\";\r\n        private const String GET_ALL_");
            
            #line 33 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 33 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetAllProcedureTemplate.PackageName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 33 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetAllProcedureTemplate.ProcedureName));
            
            #line default
            #line hidden
            this.Write("\";\r\n        private const String DELETE_");
            
            #line 34 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 34 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DeleteProcedureTemplate.PackageName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 34 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DeleteProcedureTemplate.ProcedureName));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n");
            
            #line 36 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
    var getParam = GetProcedureTemplate.InParam; 
            
            #line default
            #line hidden
            this.Write("\t\tpublic bool Delete(int id)\r\n\t\t{\r\n\t\t\tint result = 0;\r\n\t\t\tvar cmd = Connection.Cr" +
                    "eateCommand();\r\n\t\t\tcmd.CommandText = DELETE_");
            
            #line 41 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(";\r\n            cmd.CommandType = CommandType.StoredProcedure;\r\n\r\n            var " +
                    "tableIdParameter = cmd.CreateParameter();\r\n            tableIdParameter.Paramete" +
                    "rName = \"");
            
            #line 45 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getParam.ParameterName));
            
            #line default
            #line hidden
            this.Write("\";\r\n            tableIdParameter.DbType = DbType.");
            
            #line 46 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getParam.Type.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n            tableIdParameter.Value = id;\r\n\r\n            cmd.Parameters.Add(tab" +
                    "leIdParameter);\r\n            result = cmd.ExecuteNonQuery();\r\n\r\n            if (" +
                    "result == 0)\r\n                return false;\r\n\r\n            return true;\r\n\t\t}\r\n\r\n" +
                    "");
            
            #line 58 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
    var getAllParam = GetAllProcedureTemplate.InParam; 
            
            #line default
            #line hidden
            this.Write("\t\tpublic IEnumerable<");
            
            #line 59 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.EntityName));
            
            #line default
            #line hidden
            this.Write("> GetAll()\r\n        {\r\n            var cmd = Connection.CreateCommand();\r\n       " +
                    "     cmd.CommandText = GET_ALL_");
            
            #line 62 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(";\r\n            cmd.CommandType = CommandType.StoredProcedure;\r\n\r\n            var " +
                    "reader = cmd.ExecuteReader();\r\n            while (reader.Read())\r\n            {\r" +
                    "\n                var item = new ");
            
            #line 68 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.EntityName));
            
            #line default
            #line hidden
            this.Write("(reader);\r\n                yield return item;\r\n            }\r\n        }\r\n\r\n      " +
                    "  public ");
            
            #line 73 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.EntityName));
            
            #line default
            #line hidden
            this.Write(" Get(int id)\r\n        {\r\n            var cmd = Connection.CreateCommand();\r\n     " +
                    "       cmd.CommandText = GET_");
            
            #line 76 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(";\r\n            cmd.CommandType = CommandType.StoredProcedure;\r\n\r\n            cmd." +
                    "AddParameter(DbType.");
            
            #line 79 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getParam.Type.Name));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 79 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getParam.ParameterName));
            
            #line default
            #line hidden
            this.Write("\", id);\r\n\r\n            var reader = cmd.ExecuteReader();\r\n            if (reader." +
                    "Read())\r\n                return new ");
            
            #line 83 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.EntityName));
            
            #line default
            #line hidden
            this.Write("(reader);\r\n            \r\n            return new ");
            
            #line 85 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.EntityName));
            
            #line default
            #line hidden
            this.Write("();\r\n        }\r\n\r\n");
            
            #line 88 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
   var outParam = InsertProcedureTemplate.OutParam;   
            
            #line default
            #line hidden
            this.Write("\t\tpublic int Save(");
            
            #line 89 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.EntityName));
            
            #line default
            #line hidden
            this.Write(" ent)\r\n        {\r\n            var cmd = Connection.CreateCommand();\r\n            " +
                    "cmd.CommandText = INSERT_");
            
            #line 92 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(";\r\n            cmd.CommandType = CommandType.StoredProcedure;\r\n\r\n\t\t\t");
            
            #line 95 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
    WriteCommandParameters(InsertProcedureTemplate); 
            
            #line default
            #line hidden
            this.Write("\r\n            cmd.AddOutParameter(DbType.");
            
            #line 97 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outParam.Type.Name));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 97 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outParam.ParameterName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\tvar reader = cmd.ExecuteReader();\r\n            if (reader.Read())\r\n      " +
                    "      {\r\n                return (");
            
            #line 101 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outParam.Type.Name));
            
            #line default
            #line hidden
            this.Write(")reader[\"");
            
            #line 101 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outParam.ParameterName));
            
            #line default
            #line hidden
            this.Write("\"];\r\n            }\r\n\r\n            return 0;\r\n\t\t}\r\n\t\t\r\n\t\t public int Update(");
            
            #line 107 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.EntityName));
            
            #line default
            #line hidden
            this.Write(" ent)\r\n        {\r\n            int result = 0;\r\n            var cmd = Connection.C" +
                    "reateCommand();\r\n            cmd.CommandText = UPDATE_");
            
            #line 111 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.TableName));
            
            #line default
            #line hidden
            this.Write(";\r\n            cmd.CommandType = CommandType.StoredProcedure;\r\n\r\n\t\t\t");
            
            #line 114 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\DALTemplate.tt"
   WriteCommandParameters(UpdateProcedureTemplate); 
            
            #line default
            #line hidden
            this.Write("\r\n            result = cmd.ExecuteNonQuery();\r\n            if(result > 0)\r\n      " +
                    "          return ent.Id;\r\n\r\n            return result;\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
