// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\user\Sources\micase-codegenerator\CodeGenerator\Templates\LogicTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class LogicTemplate : DataTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using Entities;\r\nusing DAL;\r\n\r\n");
            
            #line 9 "C:\Users\user\Sources\micase-codegenerator\CodeGenerator\Templates\LogicTemplate.tt"
 var ObjectData = templateData.ObjectData; 
            
            #line default
            #line hidden
            this.Write("namespace Logic\r\n{\r\n    public partial class ");
            
            #line 12 "C:\Users\user\Sources\micase-codegenerator\CodeGenerator\Templates\LogicTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.ObjectName));
            
            #line default
            #line hidden
            this.Write("Logic : BaseLogic<");
            
            #line 12 "C:\Users\user\Sources\micase-codegenerator\CodeGenerator\Templates\LogicTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.ObjectName));
            
            #line default
            #line hidden
            this.Write("Entity>\r\n    {\r\n        public ");
            
            #line 14 "C:\Users\user\Sources\micase-codegenerator\CodeGenerator\Templates\LogicTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.ObjectName));
            
            #line default
            #line hidden
            this.Write("Logic(IDAL<");
            
            #line 14 "C:\Users\user\Sources\micase-codegenerator\CodeGenerator\Templates\LogicTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.ObjectName));
            
            #line default
            #line hidden
            this.Write("Entity> dal) : base(dal)\r\n        {\r\n\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
