// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\TestProjectFileTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class TestProjectFileTemplate : ProjectFileTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Project ToolsVersion=\"12.0\" DefaultTarge" +
                    "ts=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\r\n  <Prop" +
                    "ertyGroup>\r\n    <Configuration Condition=\" \'$(Configuration)\' == \'\' \">Debug</Con" +
                    "figuration>\r\n    <Platform Condition=\" \'$(Platform)\' == \'\' \">AnyCPU</Platform>\r\n" +
                    "    <ProjectGuid>{B9AF6288-7A30-4459-9920-2DA0E47B1A25}</ProjectGuid>\r\n    <Outp" +
                    "utType>Library</OutputType>\r\n    <AppDesignerFolder>Properties</AppDesignerFolde" +
                    "r>\r\n    <RootNamespace>MiCaseCodeGeneratorResultTests</RootNamespace>\r\n    <Asse" +
                    "mblyName>MiCaseCodeGeneratorResultTests</AssemblyName>\r\n    <TargetFrameworkVers" +
                    "ion>v4.5</TargetFrameworkVersion>\r\n    <FileAlignment>512</FileAlignment>\r\n    <" +
                    "ProjectTypeGuids>{3AC096D0-A1C2-E12C-1390-A8335801FDAB};{FAE04EC0-301F-11D3-BF4B" +
                    "-00C04F79EFBC}</ProjectTypeGuids>\r\n    <VisualStudioVersion Condition=\"\'$(Visual" +
                    "StudioVersion)\' == \'\'\">10.0</VisualStudioVersion>\r\n    <VSToolsPath Condition=\"\'" +
                    "$(VSToolsPath)\' == \'\'\">$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(Visu" +
                    "alStudioVersion)</VSToolsPath>\r\n    <ReferencePath>$(ProgramFiles)\\Common Files\\" +
                    "microsoft shared\\VSTT\\$(VisualStudioVersion)\\UITestExtensionPackages</ReferenceP" +
                    "ath>\r\n    <IsCodedUITest>False</IsCodedUITest>\r\n    <TestProjectType>UnitTest</T" +
                    "estProjectType>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\" \'$(Configurati" +
                    "on)|$(Platform)\' == \'Debug|AnyCPU\' \">\r\n    <DebugSymbols>true</DebugSymbols>\r\n  " +
                    "  <DebugType>full</DebugType>\r\n    <Optimize>false</Optimize>\r\n    <OutputPath>b" +
                    "in\\Debug\\</OutputPath>\r\n    <DefineConstants>DEBUG;TRACE</DefineConstants>\r\n    " +
                    "<ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4</WarningLevel>\r\n  </Prope" +
                    "rtyGroup>\r\n  <PropertyGroup Condition=\" \'$(Configuration)|$(Platform)\' == \'Relea" +
                    "se|AnyCPU\' \">\r\n    <DebugType>pdbonly</DebugType>\r\n    <Optimize>true</Optimize>" +
                    "\r\n    <OutputPath>bin\\Release\\</OutputPath>\r\n    <DefineConstants>TRACE</DefineC" +
                    "onstants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4</WarningLe" +
                    "vel>\r\n  </PropertyGroup>\r\n  <ItemGroup>\r\n    <Reference Include=\"Castle.Core, Ve" +
                    "rsion=3.3.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc, processorArchit" +
                    "ecture=MSIL\">\r\n      <HintPath>..\\packages\\Castle.Core.3.3.3\\lib\\net45\\Castle.Co" +
                    "re.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>\r\n    <Referen" +
                    "ce Include=\"Moq, Version=4.5.21.0, Culture=neutral, PublicKeyToken=69f491c39445e" +
                    "920, processorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\Moq.4.5.21\\lib\\ne" +
                    "t45\\Moq.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>\r\n    <Re" +
                    "ference Include=\"nunit.core, Version=2.6.4.14350, Culture=neutral, PublicKeyToke" +
                    "n=96d09a1eb7f44a77, processorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\NU" +
                    "nitTestAdapter.WithFramework.2.0.0\\lib\\nunit.core.dll</HintPath>\r\n      <Private" +
                    ">False</Private>\r\n    </Reference>\r\n    <Reference Include=\"nunit.core.interface" +
                    "s, Version=2.6.4.14350, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, proces" +
                    "sorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\NUnitTestAdapter.WithFramewo" +
                    "rk.2.0.0\\lib\\nunit.core.interfaces.dll</HintPath>\r\n      <Private>False</Private" +
                    ">\r\n    </Reference>\r\n    <Reference Include=\"nunit.framework, Version=2.6.4.1435" +
                    "0, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77, processorArchitecture=MSIL\"" +
                    ">\r\n      <HintPath>..\\packages\\NUnitTestAdapter.WithFramework.2.0.0\\lib\\nunit.fr" +
                    "amework.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>\r\n    <Re" +
                    "ference Include=\"nunit.util, Version=2.6.4.14350, Culture=neutral, PublicKeyToke" +
                    "n=96d09a1eb7f44a77, processorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\NU" +
                    "nitTestAdapter.WithFramework.2.0.0\\lib\\nunit.util.dll</HintPath>\r\n      <Private" +
                    ">False</Private>\r\n    </Reference>\r\n    <Reference Include=\"NUnit.VisualStudio.T" +
                    "estAdapter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=4cb40d35494691ac, p" +
                    "rocessorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\NUnitTestAdapter.WithFr" +
                    "amework.2.0.0\\lib\\NUnit.VisualStudio.TestAdapter.dll</HintPath>\r\n      <Private>" +
                    "False</Private>\r\n    </Reference>\r\n    <Reference Include=\"System\" />\r\n    <Refe" +
                    "rence Include=\"System.Data\" />\r\n    <Reference Include=\"System.XML\" />\r\n  </Item" +
                    "Group>\r\n  <Choose>\r\n    <When Condition=\"(\'$(VisualStudioVersion)\' == \'10.0\' or " +
                    "\'$(VisualStudioVersion)\' == \'\') and \'$(TargetFrameworkVersion)\' == \'v3.5\'\">\r\n   " +
                    "   <ItemGroup>\r\n        <Reference Include=\"Microsoft.VisualStudio.QualityTools." +
                    "UnitTestFramework, Version=10.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d" +
                    "50a3a, processorArchitecture=MSIL\" />\r\n      </ItemGroup>\r\n    </When>\r\n    <Oth" +
                    "erwise>\r\n      <ItemGroup>\r\n        <Reference Include=\"Microsoft.VisualStudio.Q" +
                    "ualityTools.UnitTestFramework\" />\r\n      </ItemGroup>\r\n    </Otherwise>\r\n  </Cho" +
                    "ose>\r\n  <ItemGroup>\r\n");
            
            #line 84 "C:\Users\Diego\Source\Repos\micase-codegenerator\CodeGenerator\Templates\TestProjectFileTemplate.tt"
    WriteIncludes(); 
            
            #line default
            #line hidden
            this.Write("    <Compile Include=\"Properties\\AssemblyInfo.cs\" />\r\n  </ItemGroup>\r\n  <ItemGrou" +
                    "p>\r\n    <ProjectReference Include=\"..\\MiCaseCodeGeneratorResult\\MiCaseCodeGenera" +
                    "torResult.csproj\">\r\n      <Project>{6e2132a0-89f5-4cf4-8eb7-fc9eea7d653d}</Proje" +
                    "ct>\r\n      <Name>MiCaseCodeGeneratorResult</Name>\r\n    </ProjectReference>\r\n  </" +
                    "ItemGroup>\r\n  <ItemGroup>\r\n    <None Include=\"packages.config\" />\r\n  </ItemGroup" +
                    ">\r\n  <Choose>\r\n    <When Condition=\"\'$(VisualStudioVersion)\' == \'10.0\' And \'$(Is" +
                    "CodedUITest)\' == \'True\'\">\r\n      <ItemGroup>\r\n        <Reference Include=\"Micros" +
                    "oft.VisualStudio.QualityTools.CodedUITestFramework, Version=10.0.0.0, Culture=ne" +
                    "utral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n          " +
                    "<Private>False</Private>\r\n        </Reference>\r\n        <Reference Include=\"Micr" +
                    "osoft.VisualStudio.TestTools.UITest.Common, Version=10.0.0.0, Culture=neutral, P" +
                    "ublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n          <Private" +
                    ">False</Private>\r\n        </Reference>\r\n        <Reference Include=\"Microsoft.Vi" +
                    "sualStudio.TestTools.UITest.Extension, Version=10.0.0.0, Culture=neutral, Public" +
                    "KeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n          <Private>Fals" +
                    "e</Private>\r\n        </Reference>\r\n        <Reference Include=\"Microsoft.VisualS" +
                    "tudio.TestTools.UITesting, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03" +
                    "f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n          <Private>False</Private>\r" +
                    "\n        </Reference>\r\n      </ItemGroup>\r\n    </When>\r\n  </Choose>\r\n  <Import P" +
                    "roject=\"$(VSToolsPath)\\TeamTest\\Microsoft.TestTools.targets\" Condition=\"Exists(\'" +
                    "$(VSToolsPath)\\TeamTest\\Microsoft.TestTools.targets\')\" />\r\n  <Import Project=\"$(" +
                    "MSBuildToolsPath)\\Microsoft.CSharp.targets\" />\r\n  <!-- To modify your build proc" +
                    "ess, add your task inside one of the targets below and uncomment it. \r\n       Ot" +
                    "her similar extension points exist, see Microsoft.Common.targets.\r\n  <Target Nam" +
                    "e=\"BeforeBuild\">\r\n  </Target>\r\n  <Target Name=\"AfterBuild\">\r\n  </Target>\r\n  -->\r" +
                    "\n</Project>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
